#!/bin/bash

# ================================================
# 🚀 Bridge Defect Mask R-CNN 完整工作流指南
# ================================================

echo "================================================"
echo "城桥梁病害检测 AI 模型 - 完整工作流"
echo "================================================"
echo ""

# 1. 数据转换
echo "📋 流程 1️⃣  - 数据转换 (Labelme -> COCO)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "状态: ✅ 已完成"
echo "脚本: labelme2coco.py (终极防弹版)"
echo ""
echo "✓ 已转换的文件:"
echo "  • train_coco.json   (8454 张图，34743 个标注)"
echo "  • val_coco.json     (1112 张图，4509 个标注)"
echo "  • test_coco.json    (1113 张图，5450 个标注)"
echo ""
echo "✓ 自动修复:"
echo "  • Train: 288 个越界坐标已修剪"
echo "  • Val:   83 个越界坐标已修剪"
echo "  • Test:  49 个越界坐标已修剪"
echo ""

# 2. 模型训练
echo "📋 流程 2️⃣  - 模型训练 (Mask R-CNN)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "状态: 🔄 进行中"
echo "脚本: train_final.py (最终版)"
echo ""
echo "配置:"
echo "  • 模型: Mask R-CNN with ResNet50 FPN"
echo "  • 类别: 7 (6种病害 + 背景)"
echo "  • 批大小: 2"
echo "  • Epochs: 10"
echo "  • 学习率: 0.005"
echo ""
echo "📊 病害类别:"
echo "  1. Breakage (破损) - 故障区域"
echo "  2. ReinForcement (钢筋) - 暴露钢筋"
echo "  3. Comb (蜂窝) - 蜂窝状孔隙"
echo "  4. Crack (裂缝) - 表面裂纹"
echo "  5. Seepage (渗水) - 水分渗漏"
echo "  6. Hole (孔洞) - 孔洞缺陷"
echo ""
echo "📈 训练输出:"
echo "  └─ models/"
echo "     ├─ maskrcnn_bridge_epoch_1.pth"
echo "     ├─ maskrcnn_bridge_epoch_2.pth"
echo "     ├─ ..."
echo "     ├─ maskrcnn_bridge_epoch_10.pth"
echo "     └─ maskrcnn_bridge_best.pth (最佳评分)"
echo ""

# 3. 推理
echo "📋 流程 3️⃣  - 模型推理 (推理脚本)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "状态: ⏳ 等待（训练完成后进行）"
echo "脚本: inference_final.py (最终版)"
echo ""
echo "用法（训练完成后）:"
echo ""
echo "  python inference_final.py <model.pth> <image.jpg>"
echo ""
echo "示例:"
echo ""
echo "  cd /home/dingyu/Bridge_Calc"
echo "  python inference_final.py models/maskrcnn_bridge_best.pth bridge_photo.jpg"
echo ""
echo "输出:"
echo "  └─ bridge_photo_detected.jpg (带彩色标注的结果)"
echo ""

# 4. 监控
echo "📋 高级操作 - 训练监控"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 实时查看训练日志:"
echo "  tail -f /home/dingyu/Bridge_Calc/training_final_v2.log"
echo ""
echo "📁 查看生成的模型文件:"
echo "  ls -lh /home/dingyu/Bridge_Calc/models/"
echo ""
echo "⏱️ 查看训练进程:"
echo "  ps aux | grep train_final"
echo ""
echo "⚠️️ 停止训练:"
echo "  pkill -f train_final.py"
echo ""

# 5. 重要文件清单
echo "📋 重要文件清单"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "数据准备:"
echo "  ✓ /home/dingyu/Bridge_Calc/labelme2coco.py"
echo "    └─ 功能: Labelme -> COCO 转换 (含自动修剪)"
echo ""
echo "训练脚本:"
echo "  ✓ /home/dingyu/Bridge_Calc/train_final.py"
echo "    └─ 功能: Mask R-CNN 最终版训练"
echo "  • /home/dingyu/Bridge_Calc/train_maskrcnn.py (已弃用)"
echo "  • /home/dingyu/Bridge_Calc/train_maskrcnn_simple.py (已弃用)"
echo ""
echo "推理脚本:"
echo "  ✓ /home/dingyu/Bridge_Calc/inference_final.py"
echo "    └─ 功能: 模型推理与可视化"
echo "  • /home/dingyu/Bridge_Calc/inference.py (需更新)"
echo ""
echo "数据路径:"
echo "  📂 /data1/dingyu/datasets/labelme/"
echo "     ├─ train_coco.json"
echo "     ├─ val_coco.json"
echo "     └─ test_coco.json"
echo ""
echo "模型输出:"
echo "  📂 /home/dingyu/Bridge_Calc/models/"
echo "     └─ maskrcnn_bridge_epoch_*.pth"
echo ""

# 6. 预期时间
echo "📋 预期时间表"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "当前进度:"
echo "  • 数据转换: ✅ 完成"
echo "  • 模型加载: ✅ 完成"
echo "  • 训练开始: 🔄 进行中 (Epoch 1/10)"
echo ""
echo "预计完成时间:"
echo "  • 每个 Epoch: ~20-30 分钟（取决于 GPU 型号）"
echo "  • 全部 10 Epochs: 3-5 小时"
echo "  • 推理：每张图 ~1-2 秒"
echo ""
echo "GPU 利用率："
echo "  • 显存: ~2.5-3GB (batch_size=2)"
echo "  • 估计完成时间: 今天下午/晚上"
echo ""

# 7. 故障排查
echo "📋 常见问题排查"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❌ 问题: 训练卡住不动"
echo "✅ 解决: 检查 GPU 显存，重启训练"
echo "  nvidia-smi"
echo ""
echo "❌ 问题: 内存不足"
echo "✅ 解决: 减小 BATCH_SIZE 到 1"
echo ""
echo "❌ 问题: 找不到 COCO JSON 文件"
echo "✅ 解决: 确保 labelme2coco.py 已运行"
echo ""
echo "❌ 问题: 推理结果全黑"
echo "✅ 解决: 检查模型路径，确保使用了正确的 .pth 文件"
echo ""

echo ""
echo "================================================"
echo "✨ 工作流指南完毕！祝训练顺利！"
echo "================================================"
echo ""
